const version = require('./package.json').version;
console.log("\x1b[92m----------------------------------------------------------------------------------------------");
console.log("\x1b[92mTTTTTTTTTTTTTTTTTTTTTTT             CCCCCCCCCCCCC     LLLLLLLLLLL                  IIIIIIIIII");
console.log("\x1b[92mT:::::::::::::::::::::T          CCC::::::::::::C     L:::::::::L                  I::::::::I");
console.log("\x1b[92mT:::::::::::::::::::::T        CC:::::::::::::::C     L:::::::::L                  I::::::::I");
console.log("\x1b[92mT:::::TT:::::::TT:::::T       C:::::CCCCCCCC::::C     LL:::::::LL                  II::::::II");
console.log("\x1b[92mTTTTTT  T:::::T  TTTTTT      C:::::C       CCCCCC       L:::::L                      I::::I  ");
console.log("\x1b[92m        T:::::T             C:::::C                     L:::::L                      I::::I  ");
console.log("\x1b[92m        T:::::T             C:::::C                     L:::::L                      I::::I  ");
console.log("\x1b[92m        T:::::T             C:::::C                     L:::::L                      I::::I  ");
console.log("\x1b[92m        T:::::T             C:::::C                     L:::::L                      I::::I  ");
console.log("\x1b[92m        T:::::T             C:::::C                     L:::::L                      I::::I  ");
console.log("\x1b[92m        T:::::T             C:::::C                     L:::::L                      I::::I  ");
console.log("\x1b[92m        T:::::T              C:::::C       CCCCCC       L:::::L         LLLLLL       I::::I  ");
console.log("\x1b[92m      TT:::::::TT             C:::::CCCCCCCC::::C     LL:::::::LLLLLLLLL:::::L     II::::::II");
console.log("\x1b[92m      T:::::::::T              CC:::::::::::::::C     L::::::::::::::::::::::L     I::::::::I");
console.log("\x1b[92m      T:::::::::T                CCC::::::::::::C     L::::::::::::::::::::::L     I::::::::I");
console.log("\x1b[92m      TTTTTTTTTTT                   CCCCCCCCCCCCC     LLLLLLLLLLLLLLLLLLLLLLLL     IIIIIIIIII");
console.log("\x1b[92m----------------------------------------------------------------------------------------------");
console.log('\x1b[92m  BY TIBCO LABS - VERSION: ' + version);
console.log("\x1b[92m----------------------------------------------------------------------------------------------\033[0m");
