/**
 * TIBCO Discover public API
 * TIBCO Discover public API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AnalysisMetadata { 
    /**
     * TBD
     */
    state?: string;
    /**
     * TBD
     */
    message?: string;
    /**
     * TBD
     */
    createdBy?: string;
    /**
     * TBD
     */
    createdOn?: string;
    /**
     * TBD
     */
    modifiedBy?: string;
    /**
     * TBD
     */
    modifiedOn?: string;
    /**
     * TBD
     */
    lockedBy?: string;
    /**
     * TBD
     */
    lockedOn?: string;
}

