/**
 * TIBCO Discover public API
 * null
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Asset { 
    /**
     * The asset id in TIBCO Cloud Metadata
     */
    id?: string;
    /**
     * The name of asset.
     */
    name?: string;
}

