/**
 * TIBCO Discover public API
 * TIBCO Discover public API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DatasetSource { 
    /**
     * The charset encoding of the data source file
     */
    Encoding: string;
    /**
     * The escape char of the data source file
     */
    FileEscapeChar?: string;
    /**
     * The file name of the data source csv file.
     */
    FileName?: string;
    /**
     * The quote char of the data source file
     */
    FileQuoteChar?: string;
    /**
     * The separator char to parse the data source file.
     */
    FileSeparator?: string;
    /**
     * Whether the data source csv file has column headers
     */
    FileHeaders?: boolean;
    /**
     * The preferred asset id in TIBCO Cloud Metadata
     */
    MainAssetId?: number;
    /**
     * The S3 url of data source file
     */
    FilePath?: string;
    /**
     * The data source type
     */
    DatasourceType?: string;
    /**
     * The value to distinguish the application that dataset belongs to
     */
    System?: string;
    /**
     * The id of the TIBCO Cloud Metadata instance
     */
    InstanceId?: number;
    /**
     * The infrastructure id in TIBCO Cloud Metadata.
     */
    Infrastructure?: number;
}

