/**
 * TIBCO Discover public API
 * null
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Asset } from './asset';


export interface DatasetListItem { 
    /**
     * The dataset id in TIBCO Cloud Metadata
     */
    datasetid?: number;
    /**
     * The label of the dataset
     */
    label?: string;
    /**
     * The dataset description.
     */
    description?: string;
    preferredAsset?: Asset;
}

