/**
 * TIBCO Discover public API
 * TIBCO Discover public API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvestigationMetadata } from './investigationMetadata';


export interface InvestigationDetails { 
    id?: string;
    /**
     * Case data
     */
    data?: any | null;
    metadata?: Array<InvestigationMetadata>;
}

