/**
 * TIBCO Discover public API
 * TIBCO Discover public API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvestigationField } from './investigationField';
import { InvestigationState } from './investigationState';


export interface InvestigationApplication { 
    customTitle?: string;
    applicationId?: string;
    creatorId?: string;
    creatorData?: string;
    headerFields?: Array<InvestigationField>;
    detailTitle?: InvestigationField;
    showMilestone?: boolean;
    detailFields?: Array<InvestigationField>;
    states?: Array<InvestigationState>;
}

