/**
 * TIBCO Discover public API
 * TIBCO Discover public API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Mapping { 
    /**
     * TBD
     */
    caseId: string;
    /**
     * TBD
     */
    activity: string;
    /**
     * TBD
     */
    startTime: string;
    /**
     * TBD
     */
    endTime?: string;
    /**
     * TBD
     */
    scheduledStart?: string;
    /**
     * TBD
     */
    scheduledEnd?: string;
    /**
     * TBD
     */
    requester?: string;
    /**
     * TBD
     */
    resource?: string;
    /**
     * TBD
     */
    resourceGroup?: string;
    /**
     * TBD
     */
    otherAttributes?: boolean;
}

