/**
 * TIBCO Discover public API
 * TIBCO Discover public API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Schema { 
    /**
     * The column header name of the csv file.
     */
    key?: string;
    /**
     * The value type of the column, such timestamp, numeric, string, int
     */
    type?: string;
    /**
     * The timestamp format of the value. It\'s \'None\' if the type is not timestamp
     */
    format?: string;
    /**
     * The feature type. It\'s None if no featureType is set.
     */
    featureType?: string;
    /**
     * The property to describe how important the column is in process mining
     */
    importance?: string;
    /**
     * The asset id of the column in TIBCO Cloud Metadata.
     */
    id?: number;
}

