/**
 * TIBCO Discover public API
 * TIBCO Discover public API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TemplateFilterConfig { 
    /**
     * Exact name of the Spotfire Tab to Use
     */
    id: string;
    /**
     * Menu Label
     */
    label: string;
    /**
     * Indicator if this menu item is shown or not
     */
    enabled?: boolean;
    /**
     * Set the page as a default when loading a report
     */
    isDefault?: boolean;
}

