/**
 * TIBCO Discover public API
 * TIBCO Discover public API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Visualisation { 
    /**
     * TBD
     */
    Id?: string;
    /**
     * TBD
     */
    Title?: string;
    /**
     * TBD
     */
    Description?: string;
    /**
     * TBD
     */
    CreatedDate?: string;
    /**
     * TBD
     */
    CreatedTimestamp?: number;
    /**
     * TBD
     */
    CreatedByName?: string;
    /**
     * TBD
     */
    ModifiedDate?: string;
    /**
     * TBD
     */
    ModifiedTimestamp?: number;
    /**
     * TBD
     */
    ModifiedByName?: string;
    /**
     * TBD
     */
    IsFolder?: boolean;
    /**
     * TBD
     */
    ItemType?: string;
    /**
     * TBD
     */
    Size?: number;
    /**
     * TBD
     */
    Path?: string;
    /**
     * TBD
     */
    ParentId?: string;
    /**
     * TBD
     */
    Permissions?: string;
    /**
     * TBD
     */
    ParentPermissions?: string;
    /**
     * TBD
     */
    HasPreview?: boolean;
    /**
     * TBD
     */
    DisplayPath?: string;
}

